version: 2

sources:

  - name: SQL_SERVER_DBO # name of the source 
    schema: SQL_SERVER_DBO # this is the schema our raw data lives in
    database: ALUMNO24_DEV_BRONZE_DB # this is the name of our database

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 1000, period: day}
      error_after: {count: 1000, period: day}

    tables:

      - name: ADDRESSES
        loaded_at_field: _fivetran_synced
        columns:
          - name: ADDRESS_ID
          - name: ZIPCODE
          - name: COUNTRY
          - name: ADDRESS
          - name: STATE
          - name: _fivetran_DELETED
          - name: _fivetran_synced

      - name: EVENTS
        loaded_at_field: _fivetran_synced
        columns:
          - name: EVENT_ID
          - name: PAGE_URL
          - name: EVENT_TYPE
          - name: USER_ID
          - name: PRODUCT_ID
          - name: SESSION_ID
          - name: CREATED_AT
          - name: ORDER_ID
          - name: _fivetran_DELETED
          - name: _fivetran_synced
      - name: EVENTS
        loaded_at_field: _fivetran_synced
        columns:
          - name: EVENT_ID
          - name: PAGE_URL
          - name: EVENT_TYPE
          - name: USER_ID
          - name: PRODUCT_ID
          - name: SESSION_ID
          - name: CREATED_AT
          - name: ORDER_ID
          - name: _fivetran_DELETED
          - name: _fivetran_synced