version: 2

sources:
  - name: SQL_SERVER_DBO 
    # Configuración de ubicación 
    database: ALUMNO24_DEV_BRONZE_DB 
    schema: SQL_SERVER_DBO 
    # Documentación y tests 
    description: >
      Esta es la capa BRONZE de datos extraídos del servidor SQL.
    
    # Configuración de freshness
    loaded_at_field: _etl_loaded_timestamp # Campo para verificar cuándo se cargó
    freshness:
      warn_after: {count: 1000, period: day}
      error_after: {count: 1000, period: day}
      

    tables:
      - name: ADDRESSES # Nombre de la tabla
        description: Contiene información de direcciones de origen.
        loaded_at_field: _FIVETRAN_SYNCED # Aseguramos el campo de frescura a nivel de tabla

        columns:
          - name: ADDRESS_ID # CLAVE PRIMARIA
            description: Identificador único de la dirección. Es la clave primaria de la tabla.
            data_tests:
              - unique     # Debe ser único.
              - not_null   # No debe ser nulo (porque es Primary Key).
              
          - name: ZIPCODE
            description: Código postal asociado a la dirección.
            data_tests:
              - not_null   # Aseguramos que el código postal esté presente.
              
          - name: COUNTRY
            description: País donde se localiza la dirección.
            
          - name: ADDRESS
            description: La línea principal de la dirección física.

          - name: STATE
            description: Estado o provincia de la dirección.
            
          - name: _FIVETRAN_DELETED
            description: Bandera booleana que indica si el registro fue eliminado en el sistema de origen.
            data_tests:
              - accepted_values: # Aseguramos que solo contenga TRUE o FALSE
                  values: [True, False, null] # Permitimos null si el origen lo permite

          - name: _FIVETRAN_SYNCED
            description: Marca de tiempo de la última sincronización de Fivetran. Esto nos va a determinar que es un delta, que trocito de la tabla es nuevo respecto a la ultima vez que cargue
            data_tests:
              - not_null 

# PROMOS 
      - name: PROMOS 
        description: Contiene información de promociones y descuentos.
        loaded_at_field: _FIVETRAN_SYNCED

        columns:
          - name: PROMO_ID 
            description: Identificador único de la promoción.
            data_tests:
              - unique     # Debe ser único.
              - not_null   # No debe ser nulo (Primary Key).
              
          - name: DISCOUNT
            description: Porcentaje o valor del descuento aplicado por la promoción.
            data_tests:
              - not_null   # El descuento debe estar siempre presente.
              # Opcional: Podrías añadir un test genérico para asegurar que el descuento no sea negativo
              # - dbt_utils.at_least_one # o un test singular si tienes reglas de negocio

          - name: STATUS
              
          - name: _FIVETRAN_DELETED
            description: Indicador de borrado suave.
            
          - name: _FIVETRAN_SYNCED
            description: Marca de tiempo de la última sincronización.
            data_tests:
              - not_null

# 4. Usuarios
      - name: USERS
        description: Información detallada de los usuarios o clientes.
        loaded_at_field: "_FIVETRAN_SYNCED"
        
        columns:
          - name: USER_ID
            description: Clave primaria de negocio del usuario.
            tests:
              - unique
              - not_null
              
          - name: ADDRESS_ID
            description: Clave foránea a la tabla ADDRESSES.
            # Recomendación: Añade la prueba de relación si ya definiste dim_addresses
            # - relationships:
            #     to: ref('dim_addresses')
            #     field: address_id
              
          - name: FIRST_NAME
            description: Nombre de pila del usuario.
          
          - name: LAST_NAME
            description: Apellido del usuario.
            
          - name: EMAIL
            description: Correo electrónico del usuario (clave de contacto).
            tests:
              - unique # El email debería ser único
              
          - name: PHONE_NUMBER
            description: Número de teléfono de contacto.
            
          - name: TOTAL_ORDERS
            description: Número total de pedidos realizados por el usuario.
            
          - name: CREATED_AT
            description: Marca de tiempo de la creación del usuario.
            tests:
              - not_null
              
          - name: UPDATED_AT
            description: Marca de tiempo de la última actualización del usuario.

          # Metadatos de Fivetran
          - name: _FIVETRAN_SYNCED
            description: Marca de tiempo de la sincronización de Fivetran.

      
      # 5. Products
      - name: PRODUCTS
        description: Inventario y detalles de productos.
        loaded_at_field: "_FIVETRAN_SYNCED"
        
        columns:
          - name: PRODUCT_ID
            description: Clave primaria de negocio del producto.
            tests:
              - unique
              - not_null
              
          - name: NAME
            description: Nombre comercial del producto.
            
          - name: PRICE
            description: Precio unitario del producto.
            
          - name: INVENTORY
            description: Cantidad de inventario disponible.
            
          - name: _FIVETRAN_DELETED
            description: Bandera de borrado suave de Fivetran.
            
          - name: _FIVETRAN_SYNCED
            description: Marca de tiempo de la última sincronización de Fivetran.


      # 6. Orders
      - name: ORDERS
        description: Registros de transacciones de pedidos y sus métricas asociadas.
        loaded_at_field: "_FIVETRAN_SYNCED"
        
        columns:
          - name: ORDER_ID
            description: Clave primaria de negocio del pedido.
            tests:
              - unique
              - not_null
              
          - name: USER_ID
            description: Clave foránea al usuario que realizó el pedido.
            
          - name: ADDRESS_ID
            description: Clave foránea a la dirección de envío asociada al pedido.
            
          - name: PROMO_ID
            description: Clave foránea a la promoción utilizada en el pedido.
            
          - name: SHIPPING_SERVICE
            description: Servicio de mensajería utilizado.
            
          - name: SHIPPING_COST
            description: Costo del envío.
            
          - name: ORDER_COST
            description: Costo total de los productos antes de descuentos y envío.
            
          - name: ORDER_TOTAL
            description: Valor final total pagado por el cliente.
            
          - name: TRACKING_ID
            description: Número de seguimiento del envío.
            
          - name: STATUS
            description: Estado actual del pedido (e.g., 'shipped', 'delivered').
            
          - name: CREATED_AT
            description: Marca de tiempo de la creación del pedido.
            
          - name: ESTIMATED_DELIVERY_AT
            description: Fecha estimada de entrega.
            
          - name: DELIVERED_AT
            description: Fecha real de entrega.
            
          - name: _FIVETRAN_DELETED
            description: Bandera de borrado suave de Fivetran.
            
          - name: _FIVETRAN_SYNCED
            description: Marca de tiempo de la última sincronización de Fivetran.